### ISSUE TITLE
Pretrained Model on COCO dataset?

### ISSUE THREAD

**Issue by Seth-Park** [smallcorgi/Faster-RCNN_TF#120]
I was wondering if the authors can provide pretrained network on COCO trainset.
If there is not a model available I guess I would have to train from scratch, but getting the pretrained one will be a lot more convenient :)

Thanks!!

**Comment by LHagendoorn** [comment]
This implementation isn't by the authors ;) I retrained it on COCO getting these results (lower than those reported in the paper). I guess I could find a place to upload the weights if you want.

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.147
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.324
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.117
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.031
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.157
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.234
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.166
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.238
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.242
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.048
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.274
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.405

**Comment by Seth-Park** [comment]
That would be great! 
Did you have to make any significant changes to the model architecture or test code besides switching the number of classes from 21 to 81?

Many Thanks! :)

**Comment by LHagendoorn** [comment]
Not really, you can see my changes here: https://github.com/smallcorgi/Faster-RCNN_TF/compare/master...TheLaurens:master (some of the changes are for storing some of the intermediate features)

https://drive.google.com/drive/folders/0Bxxx3LB6WT1TOGlpV3k5eVhWMHc?usp=sharing
I think this should work?

**Comment by Seth-Park** [comment]
I downloaded the pretrained nets. Thanks for the help!
I will close this issue now 👍

**Comment by towardthesea** [comment]
Hi @TheLaurens 
Could you clarify how you did with COCO dataset in detail? I ran the demo with your shared trained model but I didn't got good results, i.e. recognized objects were not right in many case.

Thanks so much!

**Comment by LHagendoorn** [comment]
Well unfortunately the average precision is still only 0.147, which I suppose is fairly crap if that goes up to 1. The current best performance on MS-COCO is 0.413, which is still not great, but far better than this. The score I got with these weights are also less then those reported by the original faster-RCNN paper, though not too much. (They report 0.212)

So yeah, I have not personally visualised the results, but I do not expect it to be super great unfortunately.

Also, you can see some of the changes I made to make it work with MSCOCO [here](https://github.com/TheLaurens/ThesisProject-SCFasterRCNN9000/commit/1f0a9b4fc380ebd9253b775d1ee06634117b9e72)

**Comment by towardthesea** [comment]
Hi @TheLaurens 
So you simply downloaded the COCO dataset from their website and did the training, didn't you? Did you follow the guide from [Girshick](https://github.com/rbgirshick/py-faster-rcnn/tree/master/data) for the `coco_proposals`:
```
For COCO with Fast R-CNN, place object proposals under `coco_proposals` (inside the data directory).
```
I am trying to redo the COCO training in my system, so would like to know the details!

Thanks for the help!

**Comment by LHagendoorn** [comment]
Nope, I don't think I did, I do think it might help performance though, especially when using the MCG proposals. There were just so many litlle things wrong with the training script for COCO that I sort of stopped once I got the basics to finally work ;)

**Comment by mingyangShang** [comment]
I have a question about training with COCO: the RCNN training needs images with object regions and their classes, but COCO doesn't have these, How can it be used to train RCNN  as PASCAL be used?

**Comment by mingyangShang** [comment]
![image](https://cloud.githubusercontent.com/assets/10825007/25113343/30c86cbe-2429-11e7-8490-48711dd7af30.png)
and you mentioned the paper's result on COCO is 19.7%?

**Comment by LHagendoorn** [comment]
Coco actually has bounding boxes, in the examples they just only show the segmentation for some reason. If you [look here](http://mscoco.org/dataset/#download) at the object instance annotations you see it comes with a bbox.
Also, no, I mentioned it is 0.212
![image](https://cloud.githubusercontent.com/assets/8653104/25120274/a94416e0-241d-11e7-9aca-3e3671d6c7aa.png)
