### ISSUE TITLE
Why only scale rpn_rois and not bbox_preds at test-time?

### ISSUE THREAD

**Issue by ghost** [smallcorgi/Faster-RCNN_TF#127]
Hi,

At test time, box predictions need to be scaled to match the actual size of the input image, and the following code exists in 'test.py' which is supposed to achieve this scaling:

    if cfg.TEST.HAS_RPN:
        assert len(im_scales) == 1, "Only single-image batch implemented"
        boxes = rois[:, 1:5] / im_scales[0]

My question is, why isn't the same scaling performed for the offset predictions? I would thus have expected an additional line of code to the above: 

    if cfg.TEST.HAS_RPN:
        assert len(im_scales) == 1, "Only single-image batch implemented"
        boxes = rois[:, 1:5] / im_scales[0]
        bbox_pred = bbox_pred / im_scales[0]

Am I correct (i.e. is there a bug in the current code), or am I incorrect? 

Best,
Aleksis

**Comment by LHagendoorn** [comment]
Well I think the network is expected to learn the correct bbox predictions regardless of the size of the object, i.e. it wouldn't need the scaling?

**Comment by ghost** [comment]
Thanks for the response, TheLaurens! I do not agree with you, however. Note that the offset predictions relative to RoI proposals occur for the rescaled input image, and thus would need scaling back to the original image afterwards, as I hypothesize above. Perhaps an example can illustrate this: 

Assume an RoI has coordinates [x1, y1, x2, y2] for the rescaled input image, and assume that this RoI has IoU=0.95 with a rescaled* ground-truth instance [x1_gt, y1_gt, x2_gt, y2_gt] in the rescaled image. Denote the associated offset prediction with respect to the RoI by [delta_x1, delta_y1, delta_x2, delta_y2] . Note that at this stage, the prediction [delta_x1, delta_y1, delta_x2, delta_y2] is (hopefully) performed so as to match the rescaled ground-truth object in the image. In other words, the hope is that [x1, y1, x2, y2] - [delta_x1, delta_y1, delta_x2, delta_y2] = [x1_gt, y1_gt, x2_gt, y2_gt]. Now add a scaling factor gamma on both sides of this equation: gamma * ([x1, y1, x2, y2] - [delta_x1, delta_y1, delta_x2, delta_y2]) = gamma * [x1_gt, y1_gt, x2_gt, y2_gt].

Is it now clear that my hypothesis about rescaling also the offset prediction is true, or do you disagree with me?

* Comment on rescaled ground-truth: The ground-truth objects are rescaled in training, to match the rescaled input image, thus all computation happens with respect to rescaled input.

**Comment by ghost** [comment]
Solved! My mistake above - the offset prediction is per design scale-invariant, so the simple [x1, y1, x2, y2] - [delta_x1, delta_y1, delta_x2, delta_y2] = [x1_gt, y1_gt, x2_gt, y2_gt] is not applied. For anyone making the same mistake as I did, have a look at page 12-13 of https://arxiv.org/pdf/1311.2524.pdf.
