### ISSUE TITLE
cannot download the VGG_imagenet.npy

### ISSUE THREAD

**Issue by ChenyanWu** [smallcorgi/Faster-RCNN_TF#14]
I try to download the VGG_imagenet.npy from google drive,but meet some problems.When I have downloaded about 100M,the project stopped.I cannot download the VGG_imagenet.npy from drive! So can anyone helpful sent the VGG_imagenet.npy to my e-mail?My e-mail is wcywcy@mail.ustc.edu.cn. Thanks

**Comment by samlong-yang** [comment]
I met the same problem...

**Comment by smallcorgi** [comment]
Hi @ChenyanWu @samlong-yang 
I have reupload the VGG_imagenet.npy to another google drive.
https://drive.google.com/open?id=0B4WygwSE8o2PUFZYSEJBOW9hZnM
You can try it again.

**Comment by ChenyanWu** [comment]
Sorry,I still cannot download it.Maybe we cannot download large files using Google drive in China.Can you  put the VGG_imagenet.npy in other drives?such as one drive,baidu pan?Thanks

**Comment by smallcorgi** [comment]
I upload the files to the Dropbox, and the download link is in Readme.

**Comment by guotong1988** [comment]
I find that `VGG_imagenet.npy` is convert from caffe model. Could you give us the link of the prototxt file?
Thank you @smallcorgi

**Comment by guotong1988** [comment]
@ChenyanWu @samlong-yang Have you solved the problem?
