### ISSUE TITLE
 undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE

### ISSUE THREAD

**Issue by WLpub** [smallcorgi/Faster-RCNN_TF#144]
have anyone got this issue?

**Comment by SQuintana2017** [comment]
I also got that error:

tensorflow.python.framework.errors_impl.NotFoundError: /home/userName/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE

**Comment by amirhfarzaneh** [comment]
[](https://github.com/smallcorgi/Faster-RCNN_TF/issues/50)

**Comment by amirhfarzaneh** [comment]
This is solved here [Issue #50](https://github.com/smallcorgi/Faster-RCNN_TF/issues/50)

**Comment by WLpub** [comment]
@amirhfarzaneh thanks for your information. And I got it fixed.

**Comment by JiteshPshah** [comment]
@WLpub  Which tensorflow version was you using to fix this problem?
