### ISSUE TITLE
/lib/utils/cython_nms.so: undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by WLpub** [smallcorgi/Faster-RCNN_TF#149]
hava anybody seen this before, please help.

**Comment by WLpub** [comment]
Hi, I got this bug fixed, conda and pip install two numpy, and they conflict. Do install opencv by apt-get or pip way instead of conda.  Conda's numpy are not reconginized.

**Comment by wujiachen987** [comment]
How to solve it,re-install opencv?

**Comment by Liu98Fan** [comment]
hello，I have the same error,you said the reason is tha two numpy conflict,why you said 'do install opencv?',I want to know how you fix it..

**Comment by Liu98Fan** [comment]
@WLpub hello，I have the same error,you said the reason is tha two numpy conflict,why you said 'do install opencv?',I want to know how you fix it..

**Comment by YunhengWu-IB** [comment]
hello，I have the same error, /lib/utils/cython_nms.so: undefined symbol: PyFPE_jbuf. I have tried your way but still have the error.

**Comment by ZWJ-here** [comment]
I have anaconda environment and python environment of Ubuntu.  I deleted the anaconda environment. Then I use the python3.5 environment of Ubuntu.The problem was solved.
