### ISSUE TITLE
cudaCheckError() failed : invalid device function

### ISSUE THREAD

**Issue by miraclebiu** [smallcorgi/Faster-RCNN_TF#15]
**# # sorry to bother you, when I run the demo.py ,it shows:**

Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/rpn_cls_score:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("rpn_cls_prob_reshape:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_bbox_pred/rpn_bbox_pred:0", shape=(?, ?, ?, 36), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rois:0", shape=(?, 5), dtype=float32)
[<tf.Tensor 'conv5_3/conv5_3:0' shape=(?, ?, ?, 512) dtype=float32>, <tf.Tensor 'rois:0' shape=(?, 5) dtype=float32>]
Tensor("fc7/fc7:0", shape=(?, 4096), dtype=float32)

Loaded network /home/jmy/Desktop/Faster-RCNN_TF-master/VGGnet_fast_rcnn_iter_70000.ckpt
cudaCheckError() failed : invalid device function

but I can run the tensorflow r0.10.0 model/image/mnist/convolutional.py successfully , I don't know where is the error. 

Thank you

**Comment by smallcorgi** [comment]
Hi @miraclebiu 

You can try to change the make.sh to solve the problem,
"nvcc -std=c++11 -c -o roi_pooling_op.cu.o roi_pooling_op_gpu.cu.cc \
-I $TF_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_52"

replace sm_52 to sm_37

**Comment by miraclebiu** [comment]
Thank you @smallcorgi

It work! Sorry to sending you e-mail again, I'm a new comer in tensorflow and linux, so can you tell me the reason why to do this. And how to learn these stuff and recommand some books or webs to read?

**Comment by smallcorgi** [comment]
Hi @miraclebiu,

The flag "-arch" is depend on your GPU's architecture.

You can reference the tutorials of tensorflow website.
https://www.tensorflow.org/versions/r0.11/tutorials/index.html
