### ISSUE TITLE
Does this means the trainging has finished?

### ISSUE THREAD

**Issue by DeepStillWater** [smallcorgi/Faster-RCNN_TF#157]
Waiting for /root/netdisk/gitlab/Faster-RCNN_TF/output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_70000.ckpt to exist...
Waiting for /root/netdisk/gitlab/Faster-RCNN_TF/output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_70000.ckpt to exist...
Waiting for /root/netdisk/gitlab/Faster-RCNN_TF/output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_70000.ckpt to exist...
Waiting for /root/netdisk/gitlab/Faster-RCNN_TF/output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_70000.ckpt to exist...
Waiting for /root/netdisk/gitlab/Faster-RCNN_TF/output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_70000.ckpt to exist...

It has been going on for about 12 hours,and it always output the same things,does it means it has finished?

**Comment by hadign20** [comment]
exactly the same problem. Have you solved it yet?

**Comment by DeepStillWater** [comment]
@hadi-ghnd Not yet,but I think  the trained model  was not integrated is  the main problem.

**Comment by hadign20** [comment]
@DeepStillWater I did try changing 2 files based on [this](https://github.com/lev-kusanagi/Faster-RCNN_TF/commit/c15c4890d30db7f41530cd20a4be1aedcde3d5f6) and [this](https://github.com/lev-kusanagi/Faster-RCNN_TF/commit/7b071cc1c9ba8257c253ff7888ecf64b666a1271) pages and I think it might help.

**Comment by DeepStillWater** [comment]
@hadi-ghnd Hi,I change the files,but the output  does not include *.ckpt files.The trainging can be finished ,but the test failed due to not finding the ckpt file.

**Comment by DeepStillWater** [comment]
@hadi-ghnd Thanks a lot,I have fixed it.

**Comment by Lakung** [comment]
i followed @hadi-ghnd method, and it works. thanks a lot
