### ISSUE TITLE
error when building the cython modules

### ISSUE THREAD

**Issue by gy1874** [smallcorgi/Faster-RCNN_TF#17]
the error reads like this:

make.sh: line 8: nvcc: command not found
g++: error: roi_pooling_op.cu.o: No such file or directory

Thanks very much! @smallcorgi

**Comment by smallcorgi** [comment]
Do you install the cuda or add cuda path in your bashrc?

**Comment by jiangyuguang** [comment]
@gy1874 
how do u add cuda path in your bashrc?
i try ,but failed again .
thanks

**Comment by hzy46** [comment]
The same issue.

I'm sure I have added the cuda path into ~/.bashrc. Is it caused by the different versions of cuda and cuDNN? Mine is cuda 7.5 and cudnn v4.0. @smallcorgi

**Comment by hzy46** [comment]
Oh, I have fixed this problem. You should not only add "/usr/local/cuda" but also **"/usr/local/cuda-7.5/bin"**  into your $PATH. @jiangyuguang  @gy1874

**Comment by StevenJames1** [comment]
@hzy46 ,I add all path into ~/.bashrc as you say,but no works,can you give me some helps? 
thanks very much!
the information as follows：
maheng@master:~/code/Faster-RCNN_TF-master/lib$ make
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'utils/nms.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
rm -rf build
sh make.sh
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
/usr/local/lib/python2.7/dist-packages/tensorflow/include
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_0000087c_00000000-7_roi_pooling_op_gpu.cu.cpp1.ii".
g++: error: roi_pooling_op.cu.o:  No such file or directory

**Comment by StevenJames1** [comment]
@CharlesShang @smallcorgi Could you help me solve this error? Thanks s lot

**Comment by CharlesShang** [comment]
I think the cython is ok.

> 2 errors detected in the compilation of "/tmp/tmpxft_0000087c_00000000-7_roi_pooling_op_gpu.cu.cpp1.ii".
g++: error: roi_pooling_op.cu.o: No such file or directory

It means this line below in make.sh
```
nvcc -std=c++11 -c -o roi_pooling_op.cu.o roi_pooling_op_gpu.cu.cc \
	-I $TF_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_52
```
failed to generate  roi_pooling_op.cu.o. So you need to
- Check cuda settings

If your system is ubuntu (above 14.04), you can add `cuda.conf` file under `/etc/ld.so.conf.d/`
 # modify when needed
`sudo sh -c 'echo "/usr/local/cuda/lib64" > /etc/ld.so.conf.d/cuda.conf'`
`sudo ldconfig`

Hope this works for you

**Comment by StevenJames1** [comment]
@CharlesShang thanks a lot , I add a -D_MWAITXINTRIN_H_INCLUDED option  fix the issue. , and my version of TensorFlow is 0.8 and CUDA 7.5 and GCC 5.2.1.

But when I run the demo as follow, I meet another error. I have already download the VGGnet and put it in the Faster-RCNN_TF-master directory. Is not my tensorflow version is too low?


maheng@master:~/code/Faster-RCNN_TF-master$ python ./tools/demo.py --model VGGnet_fast_rcnn_iter_70000.ckpt 
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 750 Ti
major: 5 minor: 0 memoryClockRate (GHz) 1.189
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.76GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01:00.0)
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/rpn_cls_score:0", shape=(?, ?, ?, 18), dtype=float32)
Traceback (most recent call last):
  File "./tools/demo.py", line 114, in <module>
    net = get_network(args.demo_net)
  File "/home/maheng/code/Faster-RCNN_TF-master/tools/../lib/networks/factory.py", line 28, in get_network
    return networks.VGGnet_test()
  File "/home/maheng/code/Faster-RCNN_TF-master/tools/../lib/networks/VGGnet_test.py", line 16, in __init__
    self.setup()
  File "/home/maheng/code/Faster-RCNN_TF-master/tools/../lib/networks/VGGnet_test.py", line 46, in setup
    .reshape_layer(2,name = 'rpn_cls_score_reshape')
  File "/home/maheng/code/Faster-RCNN_TF-master/tools/../lib/networks/network.py", line 25, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/maheng/code/Faster-RCNN_TF-master/tools/../lib/networks/network.py", line 206, in reshape_layer
    int(d),tf.cast(tf.cast(input_shape[1],tf.float32)*(tf.cast(input_shape[3],tf.float32)/tf.cast(d,tf.float32)),tf.int32),input_shape[2]]),[0,2,3,1],name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1092, in reshape
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 411, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 332, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 272, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by CharlesShang** [comment]
Maybe it's your version is too low. You can try a higher version.
Also I dont think your GTX 750 Ti has enough memory. As I remember the least mem is 3GB

**Comment by StevenJames1** [comment]
thanks for you trouble

**Comment by jiangyuguang** [comment]
thanks, i will try again. @hzy46

**Comment by BingShaw** [comment]
@StevenJames1 Can you tell me how to "add a -D_MWAITXINTRIN_H_INCLUDED option", please? Your problem have been solved completely?

**Comment by sukritshankar** [comment]
Setting the following should make it work (it worked at least for me)
(1) export PATH=$PATH:/usr/local/cuda-8.0/bin/   (or your corresponding cuda path) for your terminal
(2) In make.sh file inside lib directory, do CXXFLAGS='-D_MWAITXINTRIN_H_INCLUDED'

**Comment by lyrgwlr** [comment]
@StevenJames1 
Have you solved the 'TypeError:Expected int32, got list containing Tensors of type '_Message' instead.' problem?I met the same error like you.Please help me!!!
