### ISSUE TITLE
no dataset given - Error while training end to end.

### ISSUE THREAD

**Issue by SriramGS** [smallcorgi/Faster-RCNN_TF#186]
I followed the instructions and I was able to run the demo. But when i try to train end to end I am getting this error. Can anyone help me figure this out. The command I ran is 
`
./experiments/scripts/faster_rcnn_end2end.sh $DEVICE $DEVICE_ID VGG16 pascal_voc`
error:
```
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ DEV=bash
+ DEV_ID=VGG16
+ NET=pascal_voc
+ DATASET=
+ array=($@)
+ len=3
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case $DATASET in
+ echo 'No dataset given'
No dataset given
+ exit
``` 
I am in the root directory i.e Faster-RCNN_TF. I have downloaded the imageNet model and placed ot in the data/pretrain_model(which i created). Also the VOC dataset is also in data folder and linked here itself.

**Comment by smalldriver** [comment]
do you have solved this problem??I have the same error

**Comment by YefeiGao** [comment]
1. make sure u do step "ln -s $VOCdevkit VOCdevkit2007" correctly, replace '$VOCdevkit' with its real directory.
2. run './experiments/scripts/faster_rcnn_end2end.sh $DEVICE $DEVICE_ID VGG16 pascal_voc', replace $DEVICE with GPU or CPU and $DEVICE_ID with ur device id(0/1)

**Comment by YefeiGao** [comment]
@smalldriver 
1. make sure u do step "ln -s $VOCdevkit VOCdevkit2007" correctly, replace '$VOCdevkit' with its real directory.
2. run './experiments/scripts/faster_rcnn_end2end.sh $DEVICE $DEVICE_ID VGG16 pascal_voc', replace $DEVICE with GPU or CPU and $DEVICE_ID with ur device id(0/1)

**Comment by 1992039674** [comment]
I get the same error. Then I run:
/experiments/scripts/faster_rcnn_end2end.sh gpu 3 VGG16 pascal_voc

After the train is over,please run:
python ./tools/test_net.py --device gpu --device_id 0 --weights output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_70000.ckpt --imdb voc_2007_test --cfg experiments/cfgs/faster_rcnn_end2end.yml --network VGGnet_test

作者：存在一片云
链接：https://www.jianshu.com/p/bb2933863a55
來源：简书
简书著作权归作者所有，任何形式的转载都请联系作者获得授权并注明出处。
