### ISSUE TITLE
Feed the network with an image and get the predicted bounding boxes.

### ISSUE THREAD

**Issue by thanasissdr** [smallcorgi/Faster-RCNN_TF#187]
I am sorry about this naive question, but how can I feed the trained network with an image (without any associated .xml annotation file) and get the predicted bounding boxes along with the predicted classes? 

I think I have to make some changes to the `demo.py`. When I put my images which are `1024 x 1024` I get the following errors:

```
Traceback (most recent call last):
  File "./tools/demo.py", line 142, in <module>
    demo(sess, net, im_name)
  File "./tools/demo.py", line 72, in demo
    scores, boxes = im_detect(sess, net, im)
  File "/home/ubuntu/Desktop/project/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 145, in im_detect
    blobs, im_scales = _get_blobs(im, boxes)
  File "/home/ubuntu/Desktop/project/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 97, in _get_blobs
    blobs['data'], im_scale_factors = _get_image_blob(im)
  File "/home/ubuntu/Desktop/project/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 29, in _get_image_blob
    im_orig = im.astype(np.float32, copy=True)
AttributeError: 'NoneType' object has no attribute 'astype'

```

**Comment by limwenyao** [comment]
The original script in `demo.py` has hardcoded the image names. From [here](https://github.com/smallcorgi/Faster-RCNN_TF/blob/master/tools/demo.py#L128) change the `im_names` to your image locations. If you intend to save your images to a particular location, remove [plt.draw()](https://github.com/smallcorgi/Faster-RCNN_TF/blob/master/tools/demo.py#L51) and [plt.show()](https://github.com/smallcorgi/Faster-RCNN_TF/blob/master/tools/demo.py#L137) and add `plt.savefig(directory)` to the line where you removed `plt.draw()`
