### ISSUE TITLE
Specify which GPU to use

### ISSUE THREAD

**Issue by Yuliang-Zou** [smallcorgi/Faster-RCNN_TF#20]
I noticed that in ./tools/train_net.py, although you have variable device_name to get gpu id from command line, you do not actually use it. That means this model can only be trained on the default gpu?

I am not familiar with Tensorflow. So I wonder how I can specify which gpu to use, or even use cpu.

**Comment by ICapalija** [comment]
This code uses GPU:0 as default. To specify which GPU to use you can modify the code or hide some GPUs to tensorflow. The easiest way is to hide GPUs with environment variable CUDA_VISIBLE_DEVICES (e.g. if you want to run code on GPU:1 then run "export CUDA_VISIBLE_DEVICE=1" before you run Faster-RCNN code)

**Comment by Yuliang-Zou** [comment]
@ICapalija Thank you! So what if I don't have a GPU? Can this code run on CPU as well?

**Comment by ahmedammar** [comment]
@Yuliang-Zou have a look at #28
