### ISSUE TITLE
Running demo with no boxes in result image

### ISSUE THREAD

**Issue by Jiramew** [smallcorgi/Faster-RCNN_TF#256]
Environment:
    tensorflow: 1.3.0 only on cpu
    python: 2.7.5

Script: `python ./tools/demo.py --model model_path/VGGnet_fast_rcnn_iter_70000.ckpt `

Shows no boxes with threshold over the `CONF_THRESH(0.8)`， the score in `dets` value is rather small, close to 0.

Thanks so much~

**Comment by gengkai258** [comment]
ME TOO

**Comment by gengkai258** [comment]
could you tell me how you solve it?thank you very much !
