### ISSUE TITLE
How to increase the fps for object detection?

### ISSUE THREAD

**Issue by Pratosha-29** [smallcorgi/Faster-RCNN_TF#261]
Hi,
@smallcorgi @gdelab @guoxiaolu 
I am running this algorithm currently at 0.8 seconds/frame on the GPU.
How can I increase the fps to 14/15?
Kindly help.

**Comment by guoxiaolu** [comment]
I'm confused to @ me, it seems that I‘m not related to this project.
To my knowledge, you tested it on gpu, although there is some methods to improve the speed of faster-rcnn, it is impossible to increase to 14/15 fps. You can try other object detection methods, like rfcn, ssd and light-head rcnn. These methods are faster. Besides, some model compression methods claims that they can speed up, like this https://github.com/yihui-he/channel-pruning. But it cannot speed up to 14/15.

**Comment by Pratosha-29** [comment]
https://github.com/smallcorgi/Faster-RCNN_TF/issues/202
@guoxiaolu - I came across your comment in the above link.Hence I am interested to know how can we achieve 70ms/image or 140ms/image using the Faster-RCNN algorithm on a GPU

**Comment by guoxiaolu** [comment]
sorry, I don't remember it. I change nothing when I run it. I cannot give more suggestions.

**Comment by Pratosha-29** [comment]
Thankyou
