### ISSUE TITLE
Can this code run in multiple GPUs?

### ISSUE THREAD

**Issue by KeyKy** [smallcorgi/Faster-RCNN_TF#29]
Can this code run in multiple GPUs? Thanks.

**Comment by ahmedammar** [comment]
Not as-is, you would need to assign different tensors to different gpus ... so it's possible

**Comment by ahmedammar** [comment]
I added some code that allows you to generate the timeline tracing so you can see where and when computations are being executed, this should help with multi-gpu. #28

**Comment by MXLHELLO** [comment]
> Can this code run in multiple GPUs? Thanks.

hello~can you run it on multi gpu now?
