### ISSUE TITLE
How to train a new detector?

### ISSUE THREAD

**Issue by flowice** [smallcorgi/Faster-RCNN_TF#4]
Hi!
I failed to run faster_rcnn_end2end.sh.
Can you introduce how to train a new detector?
Thank you very much!

**Comment by smallcorgi** [comment]
Hi @flowice,

You can refer to this issue #3

**Comment by Yuliang-Zou** [comment]
Hi @smallcorgi 
What if I want to train my own model based on your trained voc2007 model (from checkpoint, not imagenet pickle file)? I mean, suppose I want to change the number of classes, and add more fc layers to fine-tune the model on my own dataset. (This can be easily done in caffe implementation, not sure if you have implemented this also)

Thanks!
