### ISSUE TITLE
How to train on my own dataset

### ISSUE THREAD

**Issue by jmiller656** [smallcorgi/Faster-RCNN_TF#40]
Hey, I'm a bit confused about what format of data I'd need to pass into this model in order to train on my own dataset. Could you give me an example of what I'd need? Thanks

**Comment by sonnyhu** [comment]
Take a lookt at https://github.com/smallcorgi/Faster-RCNN_TF/issues/3. I followed the process there and it worked.

**Comment by jmiller656** [comment]
Ohhh ok, that makes a lot of sense. Thank you!
