### ISSUE TITLE
roi_pooling_op.cu.o: No such file or directory

### ISSUE THREAD

**Issue by surajitsaikia27** [smallcorgi/Faster-RCNN_TF#42]
While I am trying to make.. I am getting the error: roi_pooling_op.cu.o: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
make.sh: line 13: nvcc: command not found
g++: error: roi_pooling_op.cu.o: No such file or directory

Please suggest what I need to do

**Comment by huawang123** [comment]
Do you have to solve this problem? You can share it to me?
