### ISSUE TITLE
Error in roi_pooling_op.cc:

### ISSUE THREAD

**Issue by surajitsaikia27** [smallcorgi/Faster-RCNN_TF#44]
whenever I am trying to do make as per the instructions.. I am getting this error

In file included from roi_pooling_op.cc:25:0:
work_sharder.h:21:49: fatal error: tensorflow/core/lib/core/threadpool.h: No such file or directory
 #include "tensorflow/core/lib/core/threadpool.h"

Please advice what i am missing

**Comment by Lan1991Xu** [comment]
I think this is caused by the version of tensorflow, and I change the latest to solve this problem

**Comment by Anida-qin** [comment]
I had the same problem and my version of tensorflow is 1.0.0(CPU ) the latest version.
Have you solved this problem ?
