### ISSUE TITLE
when i run python ./tools/demo.py --model models/VGGnet_fast_rcnn_iter_70000.ckpt 

### ISSUE THREAD

**Issue by bitwangdan** [smallcorgi/Faster-RCNN_TF#47]
when i run **python ./tools/demo.py --model models/VGGnet_fast_rcnn_iter_70000.ckpt** 
I got the result like this:

usage: demo.py [-h] [--gpu GPU_ID] [--cpu] [--net {vgg16,zf}]
demo.py: error: unrecognized arguments: --model models/VGGnet_fast_rcnn_iter_70000.ckpt

how to deal with it?

**Comment by eragonruan** [comment]
try python ./tools/demo.py --model ./models/VGGnet_fast_rcnn_iter_70000.ckpt
