### ISSUE TITLE
Model Performance?

### ISSUE THREAD

**Issue by Yuliang-Zou** [smallcorgi/Faster-RCNN_TF#5]
Hi, I tested the performance on voc2007 test set. And the performance is not as good as yours. My meanAP is only about 0.5851. Do you know what might be wrong?

**Comment by smallcorgi** [comment]
Hi @Yuliang-Zou ,
How many region proposals you use per image?
You can check it in ./lib/fast_rcnn/test.py.

**Comment by Yuliang-Zou** [comment]
I've fixed that, thank you so much!
Actually I cannot test the model using test_net.py directly. It always told me that "invalid resource handle". So I wrote my own python script to test it, but forgot to set the thresh as the same as you did.
