### ISSUE TITLE
Failed when running tf.load_op_library(roi_pooling_so)

### ISSUE THREAD

**Issue by CharlesShang** [smallcorgi/Faster-RCNN_TF#7]
The message it prompted:
```
  File "/home/shang/Work/TF-Examples/tf-faster-rcnn/tools/../lib/roi_pooling_layer/roi_pooling_op.py", line 5, in <module>
    _roi_pooling_module = tf.load_op_library(filename)
  File "/home/shang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 75, in load_op_library
    raise errors._make_specific_exception(None, None, error_msg, error_code)
tensorflow.python.framework.errors.NotFoundError: /home/shang/Work/TF-Examples/tf-faster-rcnn/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```
I tried some workaround, including, changing g++ version 5 and 4.8, modifying -arch to sm_50 (platform is GTX980), adding -D_GLIBCXX_USE_CXX11_ABI=0 in g++ complie line. It seemed the roi_pooling.so could be generated correctly, but still got the same error when runing tf.load_op_library.

**Comment by HuaizhengZhang** [comment]
@CharlesShang I meet same problem with you. I tried a lot but still couldn't fix it. Did you solve it?

**Comment by CharlesShang** [comment]
@HuaizhengZhang 
Problem has been solved. But the weird thing is I have no idea how it's fixed. I just complied it again and again with different configs. 
I can post `roi_pooing.so` file if you want to see if it can work.

**Comment by HuaizhengZhang** [comment]
@CharlesShang  Thanks a lot. My Email is zhanghuaizheng@live.com

**Comment by CharlesShang** [comment]
@HuaizhengZhang Check this repo [TFFRCNN](https://github.com/CharlesShang/TFFRCNN).
I fixed some bugs and re-organize the project, coz the codes under ./lib/ is awful, you need to run _init_paths.py to add ./lib/ to sys.path.

**Comment by CharlesShang** [comment]
You can also download [roi_pooing.so](https://github.com/CharlesShang/TFFRCNN/tree/master/lib/roi_pooling_layer/roi_pooling.so) in this repo

**Comment by HuaizhengZhang** [comment]
@CharlesShang Your cuda version is 8.0 which is too high for me. Anyway, thanks for your help.

**Comment by HuaizhengZhang** [comment]
Just fix it. Someone who meets this problem can download the [roi_pooling.so](https://github.com/smallcorgi/Faster-RCNN_TF/blob/6e2a941ac250da668cf93899dbd870cc4d838773/lib/roi_pooling_layer/roi_pooling.so) document and it to lib.

**Comment by mayujsw** [comment]
hi @HuaizhengZhang , may i know how you fix this issue ? Thanks a lot ~

**Comment by ghost** [comment]
@CharlesShang I have the same issue.
your link for roi_pooling.so file is not available for downloading as the link is currently not existent. Could you post the roi_pooling.so file
