### ISSUE TITLE
cudaCheckError() failed : invalid configuration argument

### ISSUE THREAD

**Issue by eragonruan** [smallcorgi/Faster-RCNN_TF#91]
I can run demo.py using the ckpt file you provided. And I decided to train the net myself.
training seems ok. but when i using the model trained by myself to run demo.py. 
I got this error.I am really confused. Looking forward to your answers.Thanks 

Loaded network VGGnet_fast_rcnn_iter_1000.ckpt
/home/slade/OCR/tfrcnn/tools/../lib/rpn_msr/proposal_layer_tf.py:150: RuntimeWarning: invalid value encountered in greater_equal
  keep = np.where((ws >= min_size) & (hs >= min_size))[0]
cudaCheckError() failed : invalid configuration argument
(py27) slade@slade-Z170X-Gaming-3:~/OCR/tfrcnn$

**Comment by yuanluya** [comment]
Any update for this issue, exactly same cudaCheckError when using the roi_pooling layer from this repository. The network can run for several iters then break down. Thank you very much.

**Comment by eragonruan** [comment]
I turned to use CharlesShang's version. It works well for now. You can have a try

**Comment by eragonruan** [comment]
@yuanluya  I just found out why. Hope can help you.
when I use image which size is too small for training, I will get this error. 
You can try padding some zeros around the image or resize it before using it for training which can avoid this problem.

**Comment by yuanluya** [comment]
Thanks, I believe this error is related to "wrong" data input format.

**Comment by eragonruan** [comment]
@yuanluya  I have update my answer. seems 300*300 is the smallest size this network accept. Nothing to do with the white edge

**Comment by DeepDriving** [comment]
I had the same problem,  @eragonruan how did u solve it?

**Comment by eragonruan** [comment]
have you finish the training process？is this error occurs during the testing process？

**Comment by DeepDriving** [comment]
During the training process.

**Comment by DeepDriving** [comment]
Should I switch to  CharlesShang's version?

**Comment by eragonruan** [comment]
@DeepDriving Have you update make.sh and setup.py in lib/ according to your platform？ By the way, you can try Charles's version. It has a clearer structure.

**Comment by edz-o** [comment]
I agree with @eragonruan. I had the same problem when the image has a small size which could lead to an empty input for the RoI pooling layer.

**Comment by leighton613** [comment]
Hi @edz-o, I've encountered the same problem in FPN that empty input for ROI pooling lead to this error. Have you tried any solution to skip this?

**Comment by edz-o** [comment]
@leighton613 
I seem to have added the following conditional statement after line 112 in ``lib/rpn_msr/proposal_layer_tf.py`` and the problem never shows up.

```
if not keep.any():
    keep = [0]
```
